* Known issues
I started out with setuptools, and for some reason setup.py isn't copying over the static directories that aren't packages media/ and settings/

* Twango
An open source set of extensions to make setting up new django projects go more smoothly
while still retaining the flexability of the django framework.  It just provides a set of 
templates that allow you to really dive in and get started on the main project rather than
repeat the tasks you often need to perform setting up a new django project.

* Installation
It is recommended that you install twango globally ::
    : sudo pip install https://github.com/dagray/twango/tarball/master

* Usage
   Starting a new twango project:
    : twango-admin.py startproject myproject

This will give you a new project based on the default twango template.  The system is currently only designed for one template, but in the near future we won't provide more templates, but will provide a place for you to take an application skelaton you like and bake it into a twango project template 

The twango default template provides you with a virtualenvironment.  To set it up and get everything working on your local machine
go to the directory (myproject) and run the bootstrap script

    : source bootstrap.sh

There is now a management command "initapp" - this builds out a new initial app, while at the same time adding the correct values to the urls and app settings, so it will just work once you run that command


